##---------------------------------##
##      general configuration      ##
##---------------------------------##

version: 0.1.{build}
skip_tags: true
skip_branch_with_pr: true
max_jobs: 1

##---------------------------------##
##    environment configuration    ##
##---------------------------------##

image: Visual Studio 2015
init:
  - git config --global core.autocrlf input
clone_folder: c:\projects\kawa-bot
shallow_clone: true
clone_depth: 5
matrix:
  fast_finish: false

##---------------------------------##
##       build configuration       ##
##---------------------------------##

platform: 
  - Any CPU
configuration:
  - Debug
  - Release
build:
  project: src\KawaBot.sln
  parallel: true
  verbosity: normal
before_build:
  - appveyor-retry nuget restore src\KawaBot.sln

##---------------------------------##
##       tests configuration       ##
##---------------------------------##

##---------------------------------##
##      artifacts configuration    ##
##---------------------------------##

##---------------------------------##
##     deployment configuration    ##
##---------------------------------##

##---------------------------------##
##        global handlers          ##
##---------------------------------##

##---------------------------------##
##         notifications           ##
##---------------------------------##
